name: _
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - packages/build_node
  - packages/example/simple_example
  - packages/example/simple_example_support
  - packages/nodedev
  - packages/repo_support
