name: simple_example_support
description: Simple node support example.
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  process_run:
  dev_test:
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    path: ../../build_node