name: simple_example_support
description: Simple node support example.
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  path: '>=1.8.0'
  process_run:
  dev_build:
dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.14.4'
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    path: ../../build_node
resolution: workspace
