name: simple_example_support
description: Simple node support example.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: '>=1.8.0'
  process_run:
  dev_test:
dev_dependencies:
  lints:
  test: '>=1.14.4'
  # needed node dependencies
  build_runner:
  tekartik_build_node:
    path: ../../build_node
