name: tekartik_build_node
description: Build node helper
version: 0.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  build_web_compilers:
  build_runner:
  node_preamble:
  process_run:
  dev_test:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
