name: tekartik_build_node
description: Build node helper
version: 0.2.3
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  path: '>=1.7.0 <3.0.0'
  node_preamble:
  process_run: '>=1.0.0+3'
  dev_build: '>=0.16.3'

dev_dependencies:
  test: '>=1.14.4'
  lints: '>=3.0.0'
  build_web_compilers:
  build_runner:
resolution: workspace
