name: tekartik_nodedev
description: nodedev binary helper
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  dev_build:
  process_run:
  args: '>=2.5.0'
  build_runner: '>=2.4.10'
  build_version: '>=2.1.1'
  # path: ^1.8.0
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
dev_dependencies:
  lints:
  test:


executables:
  nodedev:
resolution: workspace
