name: simple_example
description: Simple node example.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  path: ">=1.9.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.11.1'
dev_dependencies:
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  # needed node dependencies
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  lints: ">=5.0.0"
  tekartik_build_node:
    path: ../../build_node
