name: simple_example
description: Simple node example.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  path: ^1.7.0
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.11.1'
dev_dependencies:
  process_run:
  test: ^1.14.4
  # needed node dependencies
  build_runner:
  build_web_compilers:
  lints:
  tekartik_build_node:
    path: ../../build_node
