name: repo_support
description: Repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  path:
  pub_semver:
  process_run: '>=0.10.3'
  test:
  dev_test:
  pedantic:
  tekartik_build_node:
    path: ../build_node