name: repo_support
description: Repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: '>=2.0.0'
  path:
  pub_semver:
  process_run: '>=0.10.3'
  test:
  dev_build:
  tekartik_build_node:
    path: ../build_node
